### ISSUE TITLE
Избавиться от ссылок на прикладные классы в Functions.cpp

### ISSUE THREAD

**Issue by kuritsynk** [DmitryIvanov1999/Lab_1#2]
https://github.com/DmitryIvanov1999/Lab_1/blob/e9392f5c33777dafed08c87ab6250aa2123d9aaa/Functions.cpp#L162

Пусть данный модуль содержит лишь общие вспомогательные функции. Функция по работе с экземпляром или набором экземпляров класса должна быть объявлен в самом классе (как метод или статический метод класса).

**Comment by DmitryIvanov1999** [comment]
Теперь все функции, которые были объявлены друж. и работали с объектами, являются статическими методами. Их описание представлено в реализации методов класса.
