### ISSUE TITLE
Использовать по возможности функции стандартной библиотеки по работе со строками

### ISSUE THREAD

**Issue by kuritsynk** [DmitryIvanov1999/Lab_1#3]
https://github.com/DmitryIvanov1999/Lab_1/blob/e9392f5c33777dafed08c87ab6250aa2123d9aaa/Functions.h#L4

Не следует изобретать свои велосипеды. Лучше поискать готовые стандартные решения.
Посмотрите, какие методы есть в ``std::string`` (используйте ее, а не ``char*``). Также, если у вас С++ 11 и выше, то и преобразования могут выполняться через ``std::stoi``.

**Comment by DmitryIvanov1999** [comment]
Блок вспомогательных функций теперь полностью удален, все заменено std-функциями.

**Comment by DmitryIvanov1999** [comment]
Задача выполнена
