### ISSUE TITLE
Не использовать магические цифры в коде, а использовать константы

### ISSUE THREAD

**Issue by kuritsynk** [DmitryIvanov1999/Lab_1#4]
https://github.com/DmitryIvanov1999/Lab_1/blob/627443142f36a05500099e3d7981a82195ef9cec/main.cpp#L93

Количество элементов в массиве - 7 - объявить константой.

**Comment by DmitryIvanov1999** [comment]
Теперь в main.cpp и Aeroflot.cpp используется числовая константа MAX_NUMBER, а не простое число.
